apiVersion: v1
kind: Service
metadata:
  name: {{ include "springconfigrecon.fullname" . }}-frontend
  labels:
    {{- include "springconfigrecon.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http-frontend
      protocol: TCP
      name: http
  selector:
    {{- include "springconfigrecon.selectorLabels" . | nindent 4 }}
